baseURL: "/"
DefaultContentLanguage: en
title: Custom SoftwarePLUS
description: By Netcomp Technologies

menu:
      main:
        - name: Home
          url: '/'
          weight: 1
        - name: About
          url: 'about/'
          weight: 2
        - name: Services
          url: 'services/'
          weight: 3
        - name: Contact
          url: 'contact/'
          weight: 4

params:
    name: 'Custom SoftwarePLUS'
    showLanguageSelector: false #true if bilingual site - false if unilingua
    usebasin: '' #endpoint for forms
    googlemap: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2799.9633148368903!2d-73.82560598421715!3d45.43024084372952!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc93fafae393647%3A0x23aec3743ffadd38!2sNetComp%20Technologies%20Inc!5e0!3m2!1sen!2sca!4v1609950957548!5m2!1sen!2sca' # Map code of Google
    gtm: 'GTM-T7ZN93Z'
    hours:
        hour1en: 'Mon to Fri - 9:00-17:00' #Footer Hours Line #1
        hour2en: 'Sat - On Demand' #Footer Hours Line #2
        hour3en: 'Sun - On Demand' #Footer Hours Line #3
    social:
        facebook: 'https://www.facebook.com/NetCompTechnologies'
        twitter: ''
        pinterest: ''
        instagram: ''
        linkedin: 'https://www.linkedin.com/company/netcomptechnologies'
    schema:
        type: ProfessionalService
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Mo-Fr 9:00-17:00'
        logo: "img/logo.png"
        logofooter: "img/logo.png"
        image: "img/og.jpg"
        address: 15 Cartier Ave,
        address2: 'Suite 3B,'
        city: Pointe-Claire
        region: QC
        country: Canada
        postalcode: H9S 4R5
        phone: +1-438-800-7544
        email: info@netcomp.ca

enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart